webtalk_init -webtalk_dir C:/Users/Malaka/Desktop/Nanoprocessor_Project/Nanoprocessor_Project/Nanoprocessor_Project.sim/sim_1/behav/xsim/xsim.dir/TB_Register_Bank_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 23 21:58:37 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fb393ac9-6f2b-4b5e-b4cd-bf33e3d1d8fa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f5d1d4f49fba4269b6b2ec9504bba21b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12650H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7180_KB" -context "xsim\\usage"
webtalk_transmit -clientid 83366622 -regid "" -xml C:/Users/Malaka/Desktop/Nanoprocessor_Project/Nanoprocessor_Project/Nanoprocessor_Project.sim/sim_1/behav/xsim/xsim.dir/TB_Register_Bank_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Malaka/Desktop/Nanoprocessor_Project/Nanoprocessor_Project/Nanoprocessor_Project.sim/sim_1/behav/xsim/xsim.dir/TB_Register_Bank_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Malaka/Desktop/Nanoprocessor_Project/Nanoprocessor_Project/Nanoprocessor_Project.sim/sim_1/behav/xsim/xsim.dir/TB_Register_Bank_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
